language: c

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
  - sudo apt-get install -qq libcairo2-dev libspectre-dev librsvg2-dev libpoppler-glib-dev ghostscript

install:
  - ./travis-tool.sh r_install lattice cluster colorspace survival grImport
  - ./travis-tool.sh r_binary_install XML png jpeg base64enc
  - ./travis-tool.sh github_package sjp/grImport2
  - ./travis-tool.sh install_deps

script:
  - ./travis-tool.sh run_tests

after_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change
